# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a50tcsg325-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.cache/wt [current_project]
set_property parent.project_path C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/bistabil.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/counter_timp_ramas.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/ssd.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/mux2_1_afis.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/calcul_timp.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/calcul_temp.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/divizor2sec.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/divizor1min.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/divizor200Hz.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/counter10min.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/counter20min.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/counter1min.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/verif_poate_incepe.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/incalzire_apa.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/imports/new/debouncer_30ns.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/registru_9biti.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/mux2_1_setari_program.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/memorieROM.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/encoder.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/UE.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/UC.vhd
  C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/sources_1/new/main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/constrs_1/imports/Cursuri/Nexys-A7-100T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/maria/Desktop/uni/proiectPSN/Proiect.2/Proiect/Proiect.srcs/constrs_1/imports/Cursuri/Nexys-A7-100T-Master.xdc]


synth_design -top main -part xc7a50tcsg325-1


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
